spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost/product
    driver-class-name: com.mysql.jdbc.Driver
